cd libxml2-2.7.8
~/Dev/emscripten/emmake make
cd ..

# Note: libz.a generated by EM_SAVE_DIR=1 python tests/runner.py test_zlib

# Test:
#~/Dev/emscripten/emcc -O2 libxml2-2.7.8/xmllint.o libxml2-2.7.8/.libs/libxml2.a libz.a -o xmllint.test.js --embed-file test.xml --embed-file test.xsd
# js xmllint.test.js --noout --schema test.xsd test.xml

# Production
~/Dev/emscripten/emcc -O2 libxml2-2.7.8/xmllint.o libxml2-2.7.8/.libs/libxml2.a libz.a -o xmllint.raw.js --pre-js pre.js
echo "function validateXML(xml, schema) {" > xmllint.js
echo "  var Module = {" >> xmllint.js
echo "    xml: xml," >> xmllint.js
echo "    schema: schema" >> xmllint.js
echo "  };" >> xmllint.js
cat xmllint.raw.js >> xmllint.js
echo "  return Module.return;" >> xmllint.js
echo "}  " >> xmllint.js

