#!/bin/bash

rm -f xmllint-{browser.mjs,node.js} xmllint.js xmllint.wasm index-{browser.mjs,node.js} \
	index-{browser,node}.{d.ts,js.flow,mjs.flow}
rm -rf ./build
rm -rf ./libxml2/compile
rm -rf ./libxml2/m4
cd libxml2 && git clean -f && git reset --hard HEAD
