#!/bin/bash

emcc -O2 -s EMULATE_FUNCTION_POINTER_CASTS=1 \
	--memory-init-file 0 \
	./build/xmllint.o ./build/.libs/libxml2.a ./libz.a \
	-o xmllint.raw.js --pre-js ./src/pre.js

sed '/\/\* xmllint.raw.js \*\// {
	r ./xmllint.raw.js
	d
}' < ./src/wrapper.js > ./xmllint.js

if [[ "$1" == "--commonjs" ]]; then 
	echo "module.exports.validateXML = validateXML;" >> xmllint.js
fi

