#!/bin/bash

# Use Podman if it's installed. Docker otherwise.
ex="docker"
if command -v podman &> /dev/null
then
  ex="podman"
elif ! command -v docker &> /dev/null
then
  echo "Either Docker or Podman needs to be installed"
  exit 1
fi

root_dir=$(git rev-parse --show-toplevel)
container_id=$($ex build -q $root_dir/script)

$ex run --rm -v $root_dir:/src:z $container_id $@
