name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      pkg: ${{ steps.package.outputs.pkg }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    outputs:
      pkg: ${{ steps.package.outputs.pkg }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build
      - run: npm pack
      # Put the npm pack result to the output as base64 encoded string,
      # so that it can be used by other jobs
      - id: package
        run: cat xmllint-wasm-*.tgz | base64 -w 0 | sed -e 's/^/pkg=/;' >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs: [lint, build]

    strategy:
      matrix:
        node-version: [12.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: echo ${{ needs.build.outputs.pkg }} | base64 --decode > xmllint-wasm.tgz
      - run: npm install xmllint-wasm.tgz
      - run: echo "module.exports = require('xmllint-wasm')" > index-node.js
      - run: npm run check-types
      - run: npm test
