name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pkg: ${{ steps.package.outputs.pkg }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build
      - run: npm pack
      - id: package
        run: cat xmllint-wasm-*.tgz >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [12.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: echo ${{ needs.build.outputs.pkg }} > xmllint-wasm.tgz
      - run: npm install xmllint-wasm.tgz
      - run: echo "module.exports = require('xmllint-wasm')" > index-node.js
      - run: npm test
